#!/bin/bash

# multiple units can coexist

echo "TEST $0 first unit"
echo "PASS this succeeds"
echo "CODE"

echo "TEST $0 middle unit"
echo "PASS this succeeds"
echo "CODE"

echo "TEST $0 final unit"
echo "FAIL this fails"
echo "CODE"

# this example should fail because one unit failed
