#!/bin/bash

# This test script defines only test cases, delegating test unit executions
# on other test script

case "$1" in
  '') # runs all test cases
    codes=0
    RUN () { "$0" "all=$1"; codes+=$?; }
    for unit in {OK,FAIL,EUSAGE}; do RUN $unit; done
    test $codes -gt 0
    exit $?
    ;;
  all=?*) # runs all cases for that unit
    unit="${1#all=}"; codes=0
    source autotest
    run="$(autotest--root)/test/check-command"
    run="${run/$PWD/.}"
    CASE () { "$run" "unit=$unit" "$@"; codes+=$?; }

    case "$unit" in
      EUSAGE) #cases that should fail with EUSAGE
        CASE : \; --returns # missing [value]
        CASE : \; --returns '' # [value] is empty string
        CASE : \; --returns 0 13 # two integer parameters
        ;;
      FAIL) #cases that should fail with code 1 (FAIL)
        CASE false \; --returns zero
        CASE true \; --returns non-zero
        CASE true \; --returns nonzero
        CASE false \; --returns 13
        CASE true \; --returns 51
        ;;
      OK) #cases that should succed
        CASE true \; --returns zero
        CASE false \; --returns non-zero
        CASE false \; --returns nonzero
        CASE exit 13 \; --returns 13
        CASE exit 3 \; --returns -lt 5
        ;;
      *)
        echo "Bad usage: '$unit' has no cases defined" >&2
        exit 2
        ;;
    esac
    test $codes -gt 0
    exit $?
    ;;
  *)
    echo "Bad usage: invalid argument '$1'" >&2
    exit 2
    ;;
esac

##
# vim modeline
# Vim: set filetype=sh ts=2 shiftwidth=2 expandtab:
