#!/bin/bash

source "$(iai path test/autotest/utils.bash)" || exit

echo "TEST $0 any non-existing file"
EXAMPLE="$(autotest root)/example/unexistant"
test -e "$EXAMPLE" \
	&& echo "FAIL $EXAMPLE should not exist, but it does" \
	|| echo "PASS $EXAMPLE does not exist"
assert-example-status "$EXAMPLE" -eq 127
assert-example-last-code "$EXAMPLE" -eq 127
echo "CODE"

EXAMPLE="$(autotest root)/example/non-executable"
echo "TEST $0 the non-executable file $EXAMPLE"
test -x "$EXAMPLE" \
	&& echo "FAIL $EXAMPLE should not be executable, but it is" \
	|| echo "PASS $EXAMPLE is not executable"
assert-example-status "$EXAMPLE" -eq 126
assert-example-last-code "$EXAMPLE" -eq 126
echo "CODE"

##
# vim modeline
# Vim: set filetype=sh ts=2 shiftwidth=2 expandtab:
