#!/bin/bash

assert_function iai || exit

info "listing directories at /run/user/$UID/gvfs"
ls /run/user/$UID/gvfs

exit 1

find /run/user/1000/gvfs/mtp\:host\=%5Busb%3A001%2C008%5D/Almacenamiento\ interno/Download -name "*.svg" -exec mv '{}' ~/Proxectos/empresa.lorenzogrv.com/inventario/inventario-recursos/vectorart/iconos-solidarios/ \;
