#!/bin/bash

# echo "TEST $0"; echo "SKIP all tests hereafter"; exit 0

echo "TEST $0 all example files not being slow"
find "$(autotest root)/example" -type f -not -name 'slow*' -print0 \
  | while IFS= read -d '' EXAMPLE
do
  autotest "$EXAMPLE" &>/dev/null
  EXPECT=$?
  autotest report "$EXAMPLE" &>/dev/null
  ACTUAL=$?
  test $ACTUAL -eq $EXPECT \
    && echo "PASS $EXAMPLE returns exit status $EXPECT" \
    || echo "FAIL $EXAMPLE returns exit status $ACTUAL (expected $EXPECT)"
done
unset EXAMPLE EXPECT ACTUAL

# TODO slow tests

##
# vim modeline
# Vim: set filetype=sh ts=2 shiftwidth=2 expandtab:
