#!/bin/bash

source "$(iai path test/autotest/example-utils.bash)" || exit

echo "TEST $0 v1 examples considered 'assertion error'"
find-examples /v1/fail -name 'basic*' | while IFS= read -d '' EXAMPLE; do
  assert-its-executable "$EXAMPLE"
  assert-example-status "$EXAMPLE" -eq 1
  assert-example-last-code "$EXAMPLE" -eq 1
done
echo "CODE 0"

##
# vim modeline
# Vim: set filetype=sh ts=2 shiftwidth=2 expandtab:
