#!/bin/bash

##
# outputs the directory where iai resides (the "iai root").
# SEE http://stackoverflow.com/a/246128/1894803
##
iai-root () {
	local SOURCE="${BASH_SOURCE[0]}" DIR=""
	while [ -h "$SOURCE" ]; do
		DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
		SOURCE="$(readlink "$SOURCE")"
		[[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
	done
	echo "$( cd -P "$( dirname "$SOURCE" )" && pwd )"
}

##
# preparation
##

echo "Researching the environment before instalation begins..."

# defaults for all envs (aka 'standard')
BIN_PATH="/usr/local/bin"
IAI_PATH="$(iai-root)/script/standard"
RC_FILE=~/.bashrc

# overrides for 'termux' envs
if type termux-info &>/dev/null; then
  IAI_PATH="${IAI_PATH%standard}termux"
fi

# overrides for 'openwrt' envs
if type opkg &>/dev/null; then
  BIN_PATH="/usr/bin"
  RC_FILE=/etc/profile
fi

# informational messages about env detection
echo "Sumary:"
echo "> iai scripts are located at $IAI_PATH"
test -d "$IAI_PATH" || { echo "Fail: '$IAI_PATH' isn't a directory"; exit 1; }
echo "> iai scripts will be symlinked at $BIN_PATH"
test -d "$BIN_PATH" || { echo "Fail: '$BIN_PATH' isn't a directory"; exit 1; }
echo "> shell profile is located at $RC_FILE"
test -f "$RC_FILE" || { echo "Fail: '$RC_FILE' isn't a file"; exit 1; }
echo "Environment research done."

##
# the the old "install" way was:
# printf "\n$RC_LINE\n" >>$RC_FILE
# TODO deprecate and remove this
##
echo "Checking if ${RC_FILE/$HOME/"~"} contains the old installation path..."
RC_LINE="export PATH=\"\$PATH:$IAI_PATH\""
grep -q "$RC_LINE" "$RC_FILE" && {
  echo "WARN: ${RC_FILE/$HOME/"~"} contains an old-installation path line"
  echo "will remove it now"
  grep -v "$RC_LINE" "$RC_FILE" >temporal-rc-file
  mv temporal-rc-file "$RC_FILE"
  cat <<INFO
  removed the path line from ${RC_FILE/$HOME/"~"}
  to finish unistall, restart the shell
INFO
} >&2
echo "$RC_FILE check done."

##
# installation routine:
###
echo "Creating system-wide symbolic links for scripts..."
for origin in $IAI_PATH/*
do
  file="$BIN_PATH/$(basename "$origin")"
  echo "> ln -s -f ${origin/$HOME/~} $file"
  test -L "$file" && echo "  WARN: replacing existing symbolic link ($file)"
  ln -s -f $origin $file
done

echo "Installation done."

##
# vim modeline
# /* vim: set expandtab: */
# /* vim: set filetype=sh ts=2 shiftwidth=2: */
