#!/bin/bash

assert_function iai || exit

function iai-auth.su {
  local user pass
  utip "input the username"
	read user
  utip "input the password"
	read -s pass
  info "checking credentials..."
  su '$user' -c true <<<"$pass"
}

echo "-------------------------------------------------"
TESTPASS=insecure

#info "> shadow test reading credentials"; iai login && echo "OK" || echo "KO"
info "> shadow test with $TESTPASS password"
iai login <<<"lolo"$'\n'"$TESTPASS" && echo "OK" || echo "KO"

#info "> su test reading credentials"; iai-auth.su && echo "OK" || echo "KO"
info "> su test with $TESTPASS password"
iai-auth.su <<<$"lolo"$'\n'"$TESTPASS" && echo "OK" || echo "KO"

##
# vim modeline
# /* vim: set filetype=sh ts=2 shiftwidth=2: */
