#!/bin/bash

source "bash/tested.bash" || exit

source "bash/abc-basics.bash" || exit
tested "abc-basics can be sourced"

out=$(eche "some text")
err=$(eche "some text" 2>&1 1>/dev/null)
test -z "$out" && test "$err" == "some text"
tested "eche outputs nothing to stdout and given args to stderr"

# TODO _log tests
cat <<TODO
###########################################################
# TODO at file ${BASH_SOURCE[0]}
###########################################################
                    KEEP WORKING ON
                       _log tests
###########################################################
TODO
# tested 'working on _log tests'
##
# vim modeline
# /* vim: set filetype=sh ts=2 shiftwidth=2: */
