#!/bin/bash

source "$(bashido basic-array)" || { echo "can't source basic-array"; exit 1; }

# tests for array_join
a=("foo" "bar" "baz"); join="$(array_join a)"
test "$join" == "foo,bar,baz" || { echo "bad join: '$join'"; exit 1; }

echo "all basic-array tests pass"

