#!/usr/bin/env node

var iai = require('iai')

var log = iai.log
log.level = iai.Log.VERB

var read = iai.read

log.info('reading from stdin...')

read(process.stdin, { n: 1 })
  .on('readable', function () {
    var data = this.read()
    if (data) {
      log.debug('Buffer %s, data %j, utf8=%s, ascii=%s',
      data, Array.prototype.slice.call(data), data.toString('utf8'), data.toString('ascii'))
    }
  })
  .once('end', function () {
    log.warn('`process.stdin` end. Will exit now')
    process.exit(0)
  })
