#!/usr/bin/env node

var iai = require('iai')

var log = iai.log
log.level = iai.Log.VERB

var read = iai.read

log.info('reading from stdin...')

read({ n: 0 })
  .on('readable', function () {
    var data = this.read()
    if (data) {
      log.warn('data %j, utf8=%s, ascii=%s',
      Array.prototype.slice.call(data),
      JSON.stringify(data.toString('utf8')),
      data.toString('ascii'))
    }
  })
  .once('end', function () {
    log.warn('read end. Will exit now')
    process.exit(0)
  })
