#!/usr/bin/env node

var iai = require('iai')
var log = iai.log
var read = iai.readkeys

log.level = iai.Log.VERB

var server = Object.create(iai.Server)
server.on('request', require('./router'))

function readSTDIN () {
  log.info('reading from stdin...')
  read().on('readable', function () {
    var data = this.read()
    if (data) {
      server.broadcast(iai.f('stdin %s', data))
    }
  }).once('end', function () {
    log.warn('`process.stdin` end. Will exit now')
    server.broadcast('exit', function ack (err) {
      if (err) {
        log.warn('exit message not sent to clients')
        log.warn(err)
      }
    })
    process.exit(0)
  })
}

if (require.main === module) {
  var reading = false
  server.on('ws:connection', function (ws) {
    ws.on('error', function (err) {
      log.error('websocket connection error')
      log.error(err.stack)
    })
    ws.send('echo connected to server!')
    ws.on('message', function (data, flags) {
      // TODO here it's supossed to delegate logic somewhere
      log.warn('received message "%s" with flags=%j', data, flags)
      ws.send('echo received message: ' + data)
    })
    if (!reading) {
      reading = true
      readSTDIN()
    }
  })
  server.listen(27780)
}
