#!/usr/bin/env node

var iai = require('iai')
var log = iai.log
var read = iai.read

log.level = iai.Log.VERB

var server = Object.create(iai.Server)
server.on('request', require('./router'))

function readSTDIN () {
  log.info('reading from stdin...')
  read(process.stdin, { n: 1 }).on('readable', function () {
    var data = this.read()
    if (data) {
      log.debug(data)
      server.broadcast('stdin ' + data.toString())
    }
  }).once('end', function () {
    log.warn('`process.stdin` end. Will exit now')
    server.broadcast('exit', function ack (err) {
      if (err) {
        log.warn('exit message not sent to clients')
        log.warn(err)
      }
    })
    process.exit(0)
  })
}

if (require.main === module) {
  var reading = false
  server.on('ws:connection', function (ws) {
    ws.send('connected to server!')
    ws.on('message', function (data, flags) {
      if (data === 'ping') {
        ws.send('pong')
      } else if (data === 'exit') {
        log.warn('received exit!')
        ws.send('exit')
      } else {
        log.warn('received message:', data)
        ws.send('server received unknown message: ' + data)
      }
    })
    if (!reading) {
      reading = true
      readSTDIN()
    }
  })
  server.listen(27780)
}
