#!/bin/bash

source <(autotest)

echo "TEST $0"

# emulate a situation where a test takes a bit time to complete
sleep 1

# this test should pass because the time it takes to complete is short enought
true
tested "this asserion will pass"
