#!/usr/bin/env node

// DEPENDENCIES

const { basename, resolve, dirname } = require('path')
// var sources = require('../abc/lib/tool/sources');

// ARGV

var argv = process.argv.slice(2)
if (argv.length > 1 || argv[0] === '--usage' || argv[0] === '--help') {
  console.log('Usage: %s [path to file or directory]', basename(__filename))
  process.exit(1)
}

var pwd = resolve(process.cwd(), argv[0] || '')

while (pwd.length > 1) {
  try {
    // TODO if verbose console.log('TRY %s', resolve(pwd, 'package.json'))
    var pkg = require(resolve(pwd, 'package.json'))
    break
  } catch (err) {
    if (err.code !== 'MODULE_NOT_FOUND') {
      throw err
    }
    pwd = dirname(pwd)
  }
}
console.log('%s@%s %s', pkg.name, pkg.version, pwd)
