#!/bin/bash
called=$_ # to detect dependant file, $_ must be accesed on the first line
[[ $called != $0 ]] && echo "Script is being sourced" || echo "Script is being run"

echo "\$BASH_SOURCE ${BASH_SOURCE[@]}"

##
# determining path to sourced shell script
# strategy from http://unix.stackexchange.com/a/153061/49721
echo ${BASH_SOURCE[${#BASH_SOURCE[@]} - 1]}
