#!/bin/bash

autotest checkup && source <(autotest) || exit

bashido isref "api.call_trace"
tested "call_trace is a bashido reference"


teskip "write tests for the feature"

##
# vim modeline
# /* vim: set filetype=sh ts=2 shiftwidth=2: */
