#!/bin/bash

function key.help () {
  echo "---------------------------------- "
  echo "Use number keys 1-0 to select frame"
  echo "At a frame, hit 'e' to vim its file"
  echo "After editing frame will be redrawn"
  echo "Hit 'c' to create a duplicate frame"
  echo "---------------------------------- "
  echo "Hit 'h' for this help again"
  echo "Hit 'q' to exit"
}
function key.wait () {
  read -n 1; echo "press any key to continue"
}

function frame.draw () {
  clear
  echo "[frame $1]"
  cat $1
}
function frame.create () {
  if test -f $1
  then
    echo "frame already exist."
    # TODO ARE YOU SURE TO OVERWRITE
    key.wait
    return 0
  fi
  local n=${1##*.}
  local tpl="${1%%.*}.$((n-1))"
  cp "$tpl" "$1"
  echo "frame $1 created as a copy of $tpl"
  key.wait
}


key.help
name="ollo"
last=1
while read -n 1 -s char
do
  case "$char" in
    '') frame.next "$name.$last";;
    [0-9]) last=$char; frame.draw "$name.$char" ;;
    e) vim "$name.$last"; frame.draw "$name.$last" ;;
    c) frame.create "$name.$last"; frame.draw "$name.$last";;
    h) key.help ;;
    q) echo "Bye"; exit;;
    *) clear; key.help; printf 'Key "%q" has no effect\n' "$char" ;;
  esac
done
