#!/bin/bash

echo "TEST $0"
echo "PASS this is a successful assertion"
echo "CODE 0"

# exit with non-zero exit status should generate an aditional FAIL here
# because the last CODE statement reported a success exit status
exit 1
