#!/bin/bash

autotest checkup && source <(autotest) || exit

bashido isref "api.ansi"
tested "api.ansi is a valid bashido reference identifier"

teskip "there should be more tests for this"

##
# vim modeline
# /* vim: set filetype=sh ts=2 shiftwidth=2: */
