#!/bin/bash

iai info "this script should update musescore custom builds"

##
# TODO esto vai fallar en calquera outro pc que non sexa iaibox
# Para as dependencias necesarias, ver o enlace
# https://musescore.org/en/developers-handbook/compilation/compile-instructions-ubuntu-14.10-git
#
iai warn "Assuming musescore's build dependencies are installed"
iai warn "Assuming musescore's git repo is at ~/MuseScore"
cd && cd MuseScore

##
# REF: https://musescore.org/en/developers-handbook/compilation/compile-instructions-linux-bsd-git
#
iai info "Updating musescore source code..."
git checkout master
git pull

##
# TODO instalar unha revisión concreta, p. exemplo a do merge deste pull request:
# https://github.com/musescore/MuseScore/pull/2126
#
# git checkout a8d8b35b86e36d0268a4d4e701bbd2acf8c96b72

# TODO Local install
# ver https://musescore.org/en/developers-handbook/compilation/compile-instructions-linux-bsd-git#Custom-installation-path
iai info "Building musescore from source..."
make revision
make SUFFIX="-lolo" LABEL="Lolo Build"\
	|| (iai fail "Build failed. See above for details" && exit 1)
iai info "Ready to install musescore. I need root privileges..."
su -c 'make SUFFIX="-lolo" LABEL="Lolo Build" install'\
	|| (iai fail "Something failed, see above for details" && exit 1)
