#!/bin/bash


[[ "$@" =~ "--help" ]] && {
  echo "here should be some help text"
	exit 0
}

#test $# -eq 0 && exit

verb () { echo >&2 "$0: $@"; }
verb "arguments=$@"

iai-find () {
	# -O2 enables Optimization Level 2 (see `man find`)
	find -O2 "$(iai root)" \
		-path "*/.git/*" -prune -o\
		-path "*/node_modules/*" ! -name "iai*" -prune -o\
		-exec test -e /"{}/.git" \; ! -path "$(iai root)" -prune -o\
		"$@" -print
}
iai-find $@

##
# vim modeline
# /* vim: set filetype=sh ts=2 shiftwidth=2: */
