#!/bin/bash

echo "TEST $0 this is an example unit description"
echo "PASS this is a successful assertion"
echo "CODE 0"

# if ommited a TEST statement
echo "PASS this is a successful assertion"
# a CODE statement triggers a syntax error
echo "CODE 0"

# even when the continuation is correct
echo "TEST $(realpath $0) the last example unit description"
echo "PASS this is a successful assertion"
echo "CODE 0"
