#!/bin/bash

autotest checkup && source <(autotest) || exit

bashido isref "stdio.printy"
tested "stdio.printy is a valid bashido reference"

teskip "there should be some tests for this"

##
# vim modeline
# /* vim: set filetype=sh ts=2 shiftwidth=2: */
