#!/bin/bash

source <(autotest)

# TODO check-check is not a good identifier
source "$(bashido check-check)" || exit
tested "can source bashido check"

teskip "test it works with autotest"

# tests for iai-check
check that iai-check works
  check that 'which' is a command
  check that 'echo hola' outputs 'hola'
  check that returns feature works
    check that 'true' returns 0;
    check that 'false' returns 1;
  check end
  check that returns feature catches returns expected codes
    check that 'check that "exit 7" returns 7' returns 0
    check that 'check that "exit 8" returns 9' returns 1
  check end
check end

tested "an example of the check api"
##
# vim modeline
# /* vim: set filetype=sh ts=2 shiftwidth=2: */
