#!/bin/bash

source "$(bashido check)" || exit 1

check that iai is a command # functionally equivalent to the next line
check that "iai is a command (again)"; (which iai iai &>/dev/null); check end
check that iai returns 0 # functionally equivalent to the next line
check that "bare iai exits with code 0 (again)"; (iai 1>/dev/null); check end

REPO_DIR=$(git rev-parse --show-toplevel)

# iai root built-in command
check that 'iai root' outputs "$REPO_DIR"

# iai-path feature
# TODO this tests go on a separate file
# => when iai-path becomes a command?
check that 'iai path' outputs "$REPO_DIR"
check that 'iai path bin' outputs "$REPO_DIR/bin"
check that 'iai path a b c.d "f g"' outputs "$REPO_DIR/a/b/c.d/f g"
check that "iai path a b c.d 'f g'" outputs "$REPO_DIR/a/b/c.d/f g"
check that 'iai path "a b" "c d"' outputs "$REPO_DIR/a b/c d"
check that "iai path 'a b' 'c d'" outputs "$REPO_DIR/a b/c d"
check that 'iai path "a b" "c d" f g' outputs "$REPO_DIR/a b/c d/f/g"
