#!/bin/bash

autotest checkup && source <(autotest) || exit
source "$(bashido check.command)" || exit

line="iai find --help >/dev/null"
check that command "$line" code-is 0
check that command "$line" outputs nothing

line="iai find >/dev/null"
check that command "$line" code-is 0
check that command "$line" outputs nothing

line="iai find -samefile ."
check that command "$line" code-is 0
# It's no clear why it should output the absolute path
#check that command "$line" outputs "$(iai root)"

line="iai find -maxdepth 1 -type d -name test"
check that command "$line" code-is 0
# now i have nested projects, so this test got broken
#check that command "$line" outputs "$REPO_DIR/test"

line="iai find in dojo/db/fixtures/fs -type f | sort"
check that command "$line" code-is 0
check that command "$line" outputs <<STDOUT
./f000
./f00x
./f0w0
./f0wx
./fr00
./fr0x
./frw0
./frwx
STDOUT

##
# vim modeline
# /* vim: set filetype=sh ts=2 shiftwidth=2: */
