#!/bin/bash

autotest checkup && source <(autotest) || exit

echo "FAIL I am a fucking cowbow coder this time"

false
tested "This is a fucking cowboy-coded shit"

teskip "this cowbow-coded multidropbox solution works only at shitbook"

##
# vim modeline
# /* vim: set filetype=sh ts=2 shiftwidth=2: */
