#!/bin/bash

autotest checkup && source <(autotest) || exit

bashido.require "assert.common"

(
	source "iai-colors"
  assert_function "iai-colors"
)
tested "there is a command file which defines iai-colors"

teskip "there should be more tests for this, but they are not urgent"

##
# vim modeline
# /* vim: set filetype=sh ts=2 shiftwidth=2: */
