#!/bin/bash

source "$(bashido check.command)" || exit

REPO_DIR=$(git rev-parse --show-toplevel)

line="iai check abstract >/dev/null"
check.command "$line" --code-is 0
check.command "$line" --outputs nothing
##
# vim modeline
# /* vim: set filetype=sh ts=2 shiftwidth=2: */
