#!/bin/bash

source "$(bashido check.command)" || exit

line="iai find --help >/dev/null"
check that command "$line" code-is 0
check that command "$line" outputs nothing

line="iai find >/dev/null"
check that command "$line" code-is 0
check that command "$line" outputs nothing

REPO_DIR=$(git rev-parse --show-toplevel)

line="iai find -samefile ."
check that command "$line" code-is 0
check that command "$line" outputs "$(iai root)"

# now i have nested projects, so this test got broken
line="iai find -maxdepth 1 -type d -name test"
#check that command "$line" code-is 0
#check that command "$line" outputs "$REPO_DIR/test"

line="iai find in dojo/db/fixtures/fs -type f | sort"
check that command "$line" code-is 0
check that command "$line" outputs <<STDOUT
$REPO_DIR/dojo/db/fixtures/fs/f000
$REPO_DIR/dojo/db/fixtures/fs/f00x
$REPO_DIR/dojo/db/fixtures/fs/f0w0
$REPO_DIR/dojo/db/fixtures/fs/f0wx
$REPO_DIR/dojo/db/fixtures/fs/fr00
$REPO_DIR/dojo/db/fixtures/fs/fr0x
$REPO_DIR/dojo/db/fixtures/fs/frw0
$REPO_DIR/dojo/db/fixtures/fs/frwx
STDOUT

##
# vim modeline
# /* vim: set filetype=sh ts=2 shiftwidth=2: */
