#!/bin/bash

autotest checkup && source <(autotest) || exit

iai todo help &>/dev/null
tested "%s exits with code 0" 'iai todo help'

teskip "there should be some tests for this"

##
# vim modeline
# /* vim: set filetype=sh ts=2 shiftwidth=2: */
