#!/bin/bash

autotest checkup && source <(autotest) || exit

bashido isref "basic.math"
tested "basic.math is a valid bashido reference"

teskip "there should be more tests for this"

##
# vim modeline
# /* vim: set filetype=sh ts=2 shiftwidth=2: */
