#!/bin/bash

echo "TEST $0"
echo "FAIL this is a failed assertion"
echo "SKIP this is an ignored assertion"
echo "PASS this is a successful assertion"
echo "CODE"

# the example above should fail, caused by an "assertion error"
