#!/bin/bash

echo "TEST $0"

echo "PASS this is a successful assertion"
echo "SKIP this is an ignored assertion"
echo "FAIL this is a failed assertion"

# this script will exit with code 0
# exit 0 is another fail because there was a FAIL above
exit 0
