#!/bin/bash

echo "FAIL this is a failed assertion"
echo "SKIP this is an ignored assertion"
echo "PASS this is a successful assertion"

# this script will exit with code 0
# exit 0 is another fail because there was a FAIL above
exit 0
