#!/bin/bash

echo "TEST $0"
echo "FAIL this fails"
echo "CODE 1"

echo "TEST $0"
echo "SKIP this is ignored"
echo "CODE 0"

# this script will exit with code 0, and should generate an aditional FAIL
# because a CODE statement above reported a non-zero exit status
exit 0
