#!/bin/bash

echo "TEST $0"
echo "SKIP this is an ignored assertion"
# note that process exit codes above 255 are invalid
echo "CODE 256"

# this script will exit with code 0, and should generate an aditional FAIL
# because the last CODE statement reported a non-zero exit status
exit 0
