#!/bin/bash

# test units can't have childs, that's why they are units
# but any test executable may generate more than one test unit
# the following example produces perfectly valid autotest protocol

(($#)) && echo "TEST $0" "$*"

case "$*" in
  'first unit')
    echo "PASS this is a successful assertion"
    ;;
  'middle unit')
    echo "PASS this is a successful assertion"
    ;;
  'final unit')
    echo "PASS this is a successful assertion"
    ;;
  '')
    $0 first unit
    $0 middle unit
    $0 final unit
    ;;
esac

(($#)) && echo "CODE" || exit 0
