#!/bin/bash

autotest checkup && source <(autotest) || exit

# TODO check-check is not a good identifier
bashido isref check.common
tested "check.common is a valid bashido reference"

. ../../../example/testbin.bash
teskip "the simple example of the check api works"

. ../../../example/testbin-nested.bash
teskip "the nested example of the check api works"
##
# vim modeline
# /* vim: set filetype=sh ts=2 shiftwidth=2: */
